_target_: federated_methods.ppbc.ppbc.PPBC


method: 'f3ast'
theta: 0
gamma: 1

epoch_method: 'gradient_angles'
epoch_k: 3

iter_method: 'gradient_angles'
iter_k: 3

iterations: 1
need_errors: False

beta : 0.1
trust_sample_amount: 500
q_m: 1.0
