_target_: federated_methods.ppbc.ppbc.PPBC


method: 'ppbc'
theta: 0.1
gamma: 1

epoch_method: 'gradient_angles'
epoch_k: 1

iter_method: 'gradient_angles'
iter_k: 1

iterations: 3
need_errors: True

beta : 0.1
trust_sample_amount: 500
q_m: 1.0
